name: luna_track
description: "Final Year Project which is a period tracking app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  image_picker: ^1.0.4
  table_calendar: ^3.0.9
  url_launcher: ^6.1.10 
  youtube_player_flutter: ^9.1.1
  flutter_inappwebview: ^6.0.0
  flutter_svg: ^2.0.7
  khalti_flutter: ^3.0.0
  #flutter_local_notifications: ^19.1.0
  timezone: ^0.10.0
  # Add these for rapid development:
  flutter_gen_runner: ^5.3.1
  build_runner: ^2.4.6


  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/LunaTrack.jpg
    - assets/google_logo.png
    - assets/default_avatar.png
    - assets/icons/
    - assets/icons/doctor_placeholder.png