# Generated by Django 5.1.7 on 2025-04-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_reset_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='reset_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
