# Generated by Django 5.1.7 on 2025-04-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_symptom_symptomlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenstrualFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
    ]
