# Generated by Django 5.1.7 on 2025-04-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_doctor_about_doctor_education_doctor_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
