# Generated by Django 5.1.7 on 2025-04-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_appointment_payment_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=8),
        ),
    ]
