# Generated by Django 5.1.7 on 2025-04-19 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('log_period', 'Log Period'), ('take_med', 'Take Medicine'), ('log_symptom', 'Log Symptom'), ('drink_water', 'Drink Water'), ('custom', 'Custom')], max_length=20)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('time', models.TimeField()),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
