# Generated by Django 5.1.7 on 2025-04-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('log_period', 'Log Your Period'), ('next_period_start', 'Upcoming Period Start'), ('fertile_window_start', 'Fertile Window Begins'), ('ovulation_day', 'Ovulation Day'), ('custom', 'Custom Reminder')], max_length=30),
        ),
    ]
