# Generated by Django 5.1.7 on 2025-04-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_reminder_reminder_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('log_period', 'Log Your Period'), ('next_period_start', 'Upcoming Period Start'), ('fertile_window_start', 'Fertile Window Begins'), ('ovulation_day', 'Ovulation Day'), ('appointment_booked', 'Appointment Booked'), ('appointment_reminder', 'Appointment Reminder'), ('appointment_rescheduled', 'Appointment Rescheduled'), ('doctor_new_appointment', 'Doctor New Appointment'), ('doctor_rescheduled', 'Doctor Appointment Rescheduled'), ('doctor_day_reminder', 'Same-Day Appointment Reminder'), ('custom', 'Custom Reminder')], max_length=40),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
